import React from 'react';
import {AbsoluteFill, Audio, Easing, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {NARRATION, type Line} from '../text';
import {H, W} from '../theme';
import {Subtitle} from '../ui/Subtitle';
import {Balance} from './Balance';
import {DEATH_LOOMS_FRAMES, DeathLooms} from './DeathLooms';
import {Grab, GRAB_FRAMES} from './Grab';
import {HARRYS_PAN_FRAMES, HarrysPan} from './HarrysPan';
import {Opening, OPENING_FRAMES} from './Opening';
import {SKULL_FRAMES, skullGrowth, SkullMountain} from './SkullMountain';

// Part 1 (00:00–00:28) on one timeline. Neighbouring shots overlap and hand
// over with a camera move — a dissolve, a pan across, a tilt up, a fall
// into black — so nothing cuts hard and nothing needs stitching later.
type Move = 'fade' | 'pan' | 'tilt' | 'black';
const clamp = {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'} as const;

export const Shot: React.FC<{len: number; enter?: [Move, number]; exit?: [Move, number]; children: (f: number) => React.ReactNode}> = ({len, enter, exit, children}) => {
  const f = useCurrentFrame();
  const ease = Easing.inOut(Easing.cubic);
  let opacity = 1, x = 0, y = 0, blur = 0;
  if (enter) {
    const p = interpolate(f, [0, enter[1]], [0, 1], {...clamp, easing: ease});
    const q = 1 - p;
    if (enter[0] === 'pan') { x += W * 0.4 * q; blur += 10 * q; }
    if (enter[0] === 'tilt') { y -= H * 0.45 * q; blur += 10 * q; }
    opacity *= enter[0] === 'black' ? 1 : p;
  }
  if (exit) {
    const q = interpolate(f, [len - exit[1], len], [0, 1], {...clamp, easing: ease});
    if (exit[0] === 'pan') { x -= W * 0.4 * q; blur += 10 * q; }
    if (exit[0] === 'tilt') { y += H * 0.45 * q; blur += 10 * q; }
    if (exit[0] === 'fade') opacity *= 1 - q;
  }
  const fromBlack = enter?.[0] === 'black' ? interpolate(f, [0, enter[1]], [1, 0], clamp) : 0;
  return (
    <AbsoluteFill style={{opacity, transform: `translate(${x}px, ${y}px)`, filter: blur > 0.3 ? `blur(${blur}px)` : undefined}}>
      {children(f)}
      {fromBlack > 0 && <AbsoluteFill style={{background: '#000', opacity: fromBlack}} />}
    </AbsoluteFill>
  );
};

export const Sub: React.FC<{line: Line; len: number}> = ({line, len}) => {
  const f = useCurrentFrame();
  return <Subtitle line={line} opacity={interpolate(f, [0, 10, len - 10, len], [0, 1, 1, 0], clamp)} />;
};

export const T = {
  skull: 172,
  bal1: 172 + 150, // cutaway to the balance while "所以他试图征服它" is spoken
  pan: 172 + SKULL_FRAMES - 12,
  looms: 172 + SKULL_FRAMES - 12 + HARRYS_PAN_FRAMES - 10,
};
const BAL1_FRAMES = 56;
const GRAB_AT = T.looms + DEATH_LOOMS_FRAMES - 2;
const LOOKS_AT = GRAB_AT + GRAB_FRAMES - 10;
const LOOKS_FRAMES = 34;
const BAL2_AT = LOOKS_AT + LOOKS_FRAMES - 8;
const BAL2_FRAMES = 48;
export const PART1_FRAMES = BAL2_AT + BAL2_FRAMES;

// Score + sound design: generated by `npm run audio` into public/audio/.
export const Part1: React.FC = () => (
  <AbsoluteFill style={{background: '#000'}}>
    <Audio src={staticFile('audio/part1.wav')} />
    <Sequence durationInFrames={OPENING_FRAMES}>
      <Opening />
    </Sequence>
    <Sequence from={T.skull} durationInFrames={SKULL_FRAMES}>
      <Shot len={SKULL_FRAMES} enter={['fade', OPENING_FRAMES - T.skull]} exit={['pan', 12]}>{(f) => <SkullMountain frame={f} subs={false} />}</Shot>
    </Sequence>
    <Sequence from={T.bal1} durationInFrames={BAL1_FRAMES}>
      {/* the balance itself: as the mountain grows, the beam tips toward him */}
      <Shot len={BAL1_FRAMES} enter={['fade', 8]} exit={['fade', 8]}>
        {(f) => {
          const s = (T.bal1 - T.skull + f) / 24;
          const tilt = interpolate(f, [0, BAL1_FRAMES], [2, 14], {...clamp, easing: Easing.inOut(Easing.quad)});
          return <Balance frame={f} tilt={tilt} growth={skullGrowth(s)} others={1} push={f / BAL1_FRAMES} />;
        }}
      </Shot>
    </Sequence>
    <Sequence from={T.pan} durationInFrames={HARRYS_PAN_FRAMES}>
      <Shot len={HARRYS_PAN_FRAMES} enter={['pan', 12]} exit={['tilt', 10]}>{(f) => <HarrysPan frame={f} />}</Shot>
    </Sequence>
    <Sequence from={T.looms} durationInFrames={DEATH_LOOMS_FRAMES}>
      <Shot len={DEATH_LOOMS_FRAMES} enter={['tilt', 10]}>{(f) => <DeathLooms frame={f} />}</Shot>
    </Sequence>
    <Sequence from={GRAB_AT} durationInFrames={GRAB_FRAMES}>
      <Shot len={GRAB_FRAMES} enter={['black', 6]}>{(f) => <Grab frame={f} />}</Shot>
    </Sequence>
    <Sequence from={LOOKS_AT} durationInFrames={LOOKS_FRAMES}>
      {/* Voldemort on his summit looking down, cloak thrown out by the wind */}
      <Shot len={LOOKS_FRAMES} enter={['fade', 10]}>
        {(f) => <SkullMountain frame={f + SKULL_FRAMES} hold={SKULL_FRAMES} subs={false} flutter={1} cam={{z: 2.3 - 0.3 * (f / LOOKS_FRAMES), cx: 780, cy: 250 + 30 * (f / LOOKS_FRAMES)}} />}
      </Shot>
    </Sequence>
    <Sequence from={BAL2_AT} durationInFrames={BAL2_FRAMES}>
      {/* Harry has been taken off his pan: the balance falls almost all the way */}
      <Shot len={BAL2_FRAMES} enter={['fade', 8]}>
        {(f) => <Balance frame={f + 60} tilt={interpolate(f, [0, 30], [16, 25], {...clamp, easing: Easing.out(Easing.cubic)})} growth={1} others={0} harry={0} push={1 + f / BAL2_FRAMES} />}
      </Shot>
    </Sequence>
    <Sequence from={T.skull + 82} durationInFrames={62}>
      <Sub line={NARRATION.feared} len={62} />
    </Sequence>
    <Sequence from={T.skull + 154} durationInFrames={76}>
      <Sub line={NARRATION.conquer} len={76} />
    </Sequence>
  </AbsoluteFill>
);
